### ISSUE TITLE
Handle empty input EditText in Frontend

### ISSUE THREAD

**Issue by kevinzhao-tech** [321-PoM/findmy#110]
In the various EditText elements, there is no logic to handle an empty textbox upon submit. This crashes the app.

```
FATAL EXCEPTION: main
Process: com.example.findmy, PID: 3369
java.lang.NumberFormatException: For input string: ""
	at java.lang.Integer.parseInt(Integer.java:627)
	at java.lang.Integer.parseInt(Integer.java:650)
	at com.example.findmy.ui.profile.MyPOIBottomSheet.getListingPrice(MyPOIBottomSheet.java:117)
	at com.example.findmy.ui.profile.MyPOIBottomSheet.access$000(MyPOIBottomSheet.java:28)
	at com.example.findmy.ui.profile.MyPOIBottomSheet$1.onClick(MyPOIBottomSheet.java:33)
	at android.view.View.performClick(View.java:7125)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1213)
	at android.view.View.performClickInternal(View.java:7102)
	at android.view.View.access$3500(View.java:801)
	at android.view.View$PerformClick.run(View.java:27336)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by kevinzhao-tech** [comment]
Fixed with https://github.com/321-PoM/findmy/commit/81220ea796209eab10647b5f6dab03b056847288
