### ISSUE TITLE
Switching Fragments too quickly crashes the app

### ISSUE THREAD

**Issue by kevinzhao-tech** [321-PoM/findmy#111]
Sometimes a response can be received when the fragment has switched away. Causing this:
```
FATAL EXCEPTION: main
Process: com.example.findmy, PID: 3485
java.lang.IllegalStateException: Fragment ProfileFragment{8d7d8ef} (6a1bf479-637f-46f1-bf46-ac527c3491d1) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:972)
	at com.example.findmy.ui.profile.ProfileFragment$3.onFailure(ProfileFragment.java:151)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onFailure$1$retrofit2-DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:96)
	at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

This should be fixed by killing all enqueued requests upon `onPause()`

**Comment by jorido** [comment]
Seems like the context is not yet attached at the scope of `requireContext()` used in these fragments, I will just add null checking for the contexts when we use `requireContext()`

**Comment by kevinzhao-tech** [comment]
Seems to be fixed. Closing for now...
