### ISSUE TITLE
JEST bug | The requested module '../server.js' does not provide an export named 'httpServer'

### ISSUE THREAD

**Issue by anjjunsu** [321-PoM/findmy#197]
```
Test Suites: 6 failed, 6 total
Tests:       0 total
Snapshots:   0 total
Time:        3.182 s
Ran all test suites.
file:///home/runner/work/findmy/findmy/backend/tests/teardown.mjs:2
import { httpServer, httpsServer } from "../server.js"
         ^^^^^^^^^^
SyntaxError: The requested module '../server.js' does not provide an export named 'httpServer'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:131:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:213:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:431:15)
    at async requireOrImportModule (/home/runner/work/findmy/findmy/backend/node_modules/jest-util/build/requireOrImportModule.js:55:32)
    at async ScriptTransformer.requireAndTranspileModule (/home/runner/work/findmy/findmy/backend/node_modules/@jest/transform/build/ScriptTransformer.js:798:22)
    at async runGlobalHook (/home/runner/work/findmy/findmy/backend/node_modules/@jest/core/build/runGlobalHook.js:101:9)
    at async runJest (/home/runner/work/findmy/findmy/backend/node_modules/@jest/core/build/runJest.js:374:5)
    at async _run10000 (/home/runner/work/findmy/findmy/backend/node_modules/@jest/core/build/cli/index.js:343:7)
    at async runCLI (/home/runner/work/findmy/findmy/backend/node_modules/@jest/core/build/cli/index.js:198:3)
Error: Process completed with exit code 1.
```

**Comment by muhan-alan-li** [comment]
@anjjunsu was this run on the branch 149-APITests? 

![image](https://github.com/321-PoM/findmy/assets/85966696/1c5dfe81-2f8f-45d3-b15e-4b327e3415f6)
this is what `server.js` should look like

**Comment by muhan-alan-li** [comment]
okay i read the logs and I have no idea why its not working, it also seems to have trouble recognizing imports, I'm guessing it might be an issue with specifying .cjs vs .mjs
